#!/usr/bin/env python3
"""Generate the Argo CD Application manifest for the practice app.

The repo URL is read from `git remote get-url origin`, so nothing user-specific
is ever committed - each clone generates its own manifest. Works the same on
Linux, WSL, and Windows (any Python 3.9+).

Output: argocd/generated/practice-app.yaml  (git-ignored)
Apply:  make app-deploy   (or kubectl apply -f argocd/generated/practice-app.yaml)
"""
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "argocd" / "generated"


def repo_https_url() -> str:
    try:
        url = subprocess.check_output(
            ["git", "-C", str(REPO), "remote", "get-url", "origin"], text=True
        ).strip()
    except subprocess.CalledProcessError:
        sys.exit("gen-argocd-app: no 'origin' git remote - push this repo to GitHub first.")
    # Normalize ssh form (git@github.com:owner/repo.git) to https for Argo CD.
    if url.startswith("git@"):
        host, path = url.removeprefix("git@").split(":", 1)
        url = f"https://{host}/{path}"
    if not url.endswith(".git"):
        url += ".git"
    return url


def main() -> int:
    url = repo_https_url()
    manifest = f"""# Generated by scripts/gen-argocd-app.py - do not edit, do not commit.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: practice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {url}
    targetRevision: main
    path: helm/practice-app
  destination:
    server: https://kubernetes.default.svc
    namespace: practice-app
  # Sync is MANUAL on purpose - pressing the button (and turning on automation)
  # is part of the GitOps scenario.
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
"""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "practice-app.yaml"
    out.write_text(manifest)
    print(f"gen-argocd-app: wrote {out.relative_to(REPO)} (repoURL: {url})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
