#!/usr/bin/env python3
"""Generate the Argo CD Application manifest for the practice app.

Argo reads the in-cluster git server when it exists and GitHub otherwise. Either
way the URL is derived, never committed, so nothing user-specific lands in git.
Works the same on Linux, WSL, and Windows (any Python 3.9+).

Output: argocd/generated/practice-app.yaml  (git-ignored)
Apply:  make app-deploy   (or kubectl apply -f argocd/generated/practice-app.yaml)
"""
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_argocd_app_url import repo_https_url

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "argocd" / "generated"


def source_repo_url() -> "tuple[str, bool]":
    """Argo reads cluster git when it exists, GitHub otherwise.

    One Application, permanently. Cluster git is the source; GitHub is the upstream
    the workspace pushes to. Falling back keeps the toggle honest: with
    enable_cluster_git = false everything behaves exactly as it did before.

    The fallback is not a hole in the self-contained git rule. It is the pre-drill
    path, reached only when the toggle is off, which is how this repo behaved for
    everyone before the drill existed. On the drill path the toggle is on and the
    fallback is unreachable. What the rule forbids is Argo reading GitHub while a
    drill is running, and that cannot happen here.

    Returns the URL and whether it came from cluster git, because the sync policy
    follows the source - see render().
    """
    out = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "bootstrap.py"),
         "dev", "output", "-raw", "cluster_git_url"],
        capture_output=True,
        text=True,
    )
    url = out.stdout.strip() if out.returncode == 0 else ""
    if url:
        print(f"gen-argocd-app: pointing Argo CD at cluster git ({url})", file=sys.stderr)
        return url, True
    print("gen-argocd-app: cluster git is off - pointing Argo CD at GitHub", file=sys.stderr)
    return repo_https_url(), False


def render(url: str, cluster_git: bool) -> str:
    """The Application manifest. Sync policy follows the source, deliberately.

    Two callers share this one Application and they want opposite things.

    On the drill path (cluster git) sync must be automated. The learner edits an
    image tag in the browser, commits and pushes, and watches Argo roll it - that
    loop is the whole point, and nothing in the drill UI presses a Sync button.

    On the pre-drill path (GitHub) sync must stay manual, because
    scenarios/09-gitops-argocd.md task 5 IS "turn on automated sync + self-heal"
    and `make check N=09` passes only once the learner has done it. Emitting it by
    default would pre-solve the exercise and make its own check vacuous.

    `selfHeal` stays off on both paths. Polling controls detection, syncPolicy
    controls action, and selfHeal reverts drift on everything the Application
    manages - it would stomp any scenario whose exercise is an imperative kubectl
    change. It is turned on per-scenario, by the session, for scenarios that ask
    for it.
    """
    if cluster_git:
        policy = """  # Sync is AUTOMATED here because Argo is reading in-cluster git: the drill loop
  # is push-then-watch, and there is no Sync button in the drill UI to press.
  # selfHeal is off - it is per-scenario, and it would stomp any exercise whose
  # point is an imperative kubectl change.
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false"""
    else:
        policy = """  # Sync is MANUAL on purpose - pressing the button (and turning on automation)
  # is task 5 of scenarios/09-gitops-argocd.md.
  syncPolicy:
    syncOptions:
      - CreateNamespace=false"""

    return f"""# Generated by scripts/gen-argocd-app.py - do not edit, do not commit.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: practice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {url}
    targetRevision: main
    path: helm/practice-app
  destination:
    server: https://kubernetes.default.svc
    namespace: practice-app
{policy}
"""


def main() -> int:
    url, cluster_git = source_repo_url()
    manifest = render(url, cluster_git)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "practice-app.yaml"
    out.write_text(manifest)
    print(f"gen-argocd-app: wrote {out.relative_to(REPO)} (repoURL: {url})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
